### ISSUE TITLE
分析文件为空

### ISSUE THREAD

**Issue by linyimin0812** [linyimin0812/spring-startup-analyzer#1]
bean的分析信息没有，只有火焰图，如下图，xxx-analyzer.html是0字节

![image](https://github.com/linyimin0812/spring-startup-analyzer/assets/17776713/9216a498-4e02-42e4-a44b-d252def3c935)

**Comment by linyimin0812** [comment]
[fixed](https://github.com/linyimin0812/spring-startup-analyzer/commit/50f66d83c9f98159ce2527986c0241217ebe01c1)

**Comment by xuxianju** [comment]
`2023-07-20 11:28:12.813 INFO  [main] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - ==========StartupMonitor start========
2023-07-20 11:28:12.864 INFO  [main] io.github.linyimin0812.profiler.extension.enhance.jar.JarCollector - =======================JarCollector start=======================
2023-07-20 11:28:12.873 INFO  [main] io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.AsyncProfilerListener - ==============AsyncProfilerListener start========================
2023-07-20 11:28:12.875 INFO  [main] io.github.linyimin0812.profiler.common.settings.ProfilerSettings - loaded settings from /root/spring-startup-analyzer/config/spring-startup-analyzer.properties
2023-07-20 11:28:12.889 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 1 s
2023-07-20 11:28:12.973 INFO  [main] io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.AsyncProfilerListener - AsyncProfiler execute command: start,event=wall,threads,interval=5000000,total,threadnames=main, result is Profiling started

2023-07-20 11:28:13.306 INFO  [main] io.github.linyimin0812.profiler.extension.enhance.springbean.BeanCreateListener - ============BeanCreateListener start=============
2023-07-20 11:28:17.156 INFO  [main] io.github.linyimin0812.profiler.core.monitor.check.EndpointCheckService - endpoints: [http://localhost:8081/manage/actuator/health]
2023-07-20 11:28:17.180 INFO  [main] io.github.linyimin0812.profiler.core.monitor.check.TimeoutCheckService - timeout duration: 20 minutes
2023-07-20 11:28:23.891 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 11 s
2023-07-20 11:28:34.280 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 21 s
2023-07-20 11:28:44.290 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 31 s
2023-07-20 11:28:54.300 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 41 s
2023-07-20 11:29:05.117 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.core.monitor.StartupMonitor - app initializing 51 s
2023-07-20 11:29:13.882 INFO  [StartupMonitor-Thread] io.github.linyimin0812.profiler.extension.enhance.springbean.BeanCreateListener - ============BeanCreateListener stop=============
2023-07-20 11:29:14.417 WARN  [StartupMonitor-Thread] io.github.linyimin0812.profiler.extension.enhance.springbean.BeanCreateListener - profilerResultThreadLocal is not empty. There may be a problem with the initialization of the bean. [[]]`

用早上最新的release包没有analyzer.html文件生成，过程中有warn

**Comment by linyimin0812** [comment]
启动时控制台里有抛异常信息吗？

**Comment by xuxianju** [comment]
Exception in thread "StartupMonitor-Thread" java.lang.NullPointerException
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.github.linyimin0812.profiler.common.ui.StartupVO.calculateInvokeMetrics(StartupVO.java:78)
	at io.github.linyimin0812.profiler.common.ui.StartupVO.toJSONString(StartupVO.java:53)
	at io.github.linyimin0812.profiler.core.container.IocContainer.writeStartupVOToHtml(IocContainer.java:108)
	at io.github.linyimin0812.profiler.core.container.IocContainer.stop(IocContainer.java:95)
	at io.github.linyimin0812.profiler.core.monitor.StartupMonitor.checkStatus(StartupMonitor.java:44)
	at java.lang.Thread.run(Thread.java:748)

没生成html的时候有这个异常。 
我刚刚容器里多试了两次，有一个正常起来，能生成analyzer.html。

**Comment by linyimin0812** [comment]
没法在本地重现，加了个异常捕获和log，可以下载最新版本再重试一下
