### ISSUE TITLE
报告中只有火焰图，其他图看不见

### ISSUE THREAD

**Issue by bz9527** [linyimin0812/spring-startup-analyzer#149]
报告只有火焰图，其他图看不见， 日志了有warn  profilerResultThreadLocal is not empty,there may be a problem with the initialization of the bean.

**Comment by linyimin0812** [comment]
可以F12看一下有没有报错，或者看一下spring-startup-analyzer/output/*-analyzer.html文件夹的内容

**Comment by bz9527** [comment]
日志里打印，IOCcontainer  has stopped    我这个服务启动时间比较久。。有干系么？

**Comment by linyimin0812** [comment]
> 日志里打印，IOCcontainer has stopped 我这个服务启动时间比较久。。有干系么？

这个应该没关系，应该是和fasejson有关，已经替换成gson，可以下载v3.1.1版本再试试

**Comment by burhiepotdult1982** [comment]
同样只有火焰图，看了日志中有这样的报错

[err] Exception in thread "StartupMonitor-Thread" 
[err] java.lang.LinkageError: loader io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader @3d82c5f3 attempted duplicate class definition for com.google.gson.internal.$Gson$Types. (com.google.gson.internal.$Gson$Types is in unnamed module of loader io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader @3d82c5f3, parent loader 'platform')
[err] 	at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:95)
[err] 	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:70)
[err] 	at io.github.linyimin0812.profiler.common.ui.StartupVO$1.<init>(StartupVO.java:67)
[err] 	at io.github.linyimin0812.profiler.common.ui.StartupVO.toJSONString(StartupVO.java:67)
[err] 	at io.github.linyimin0812.profiler.core.container.IocContainer.writeStartupVOToHtml(IocContainer.java:156)
[err] 	at io.github.linyimin0812.profiler.core.container.IocContainer.stop(IocContainer.java:98)
[err] 	at io.github.linyimin0812.profiler.core.monitor.StartupMonitor.checkStatus(StartupMonitor.java:44)
[err] 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by burhiepotdult1982** [comment]
> 同样只有火焰图，看了日志中有这样的报错
> 
> [err] Exception in thread "StartupMonitor-Thread" [err] java.lang.LinkageError: loader io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader @3d82c5f3 attempted duplicate class definition for com.google.gson.internal.$Gson$Types. (com.google.gson.internal.$Gson$Types is in unnamed module of loader io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader @3d82c5f3, parent loader 'platform') [err] at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:95) [err] at com.google.gson.reflect.TypeToken.(TypeToken.java:70) [err] at io.github.linyimin0812.profiler.common.ui.StartupVO$1.(StartupVO.java:67) [err] at io.github.linyimin0812.profiler.common.ui.StartupVO.toJSONString(StartupVO.java:67) [err] at io.github.linyimin0812.profiler.core.container.IocContainer.writeStartupVOToHtml(IocContainer.java:156) [err] at io.github.linyimin0812.profiler.core.container.IocContainer.stop(IocContainer.java:98) [err] at io.github.linyimin0812.profiler.core.monitor.StartupMonitor.checkStatus(StartupMonitor.java:44) [err] at java.base/java.lang.Thread.run(Thread.java:1583)

添加了-Dprofiler.agent.exclude=com.google.gson
已经解决
