### ISSUE TITLE
使用 JSON.toJSONString 序列化一个 Map，当 Map 含有一个大字符串时会出现了 OOM。

### ISSUE THREAD

**Issue by hanssonHan** [linyimin0812/spring-startup-analyzer#16]
# 问题描述

使用 `JSON.toJSONString` 序列化一个Map，Map含有一个大字符串时会出现了OOM。

# 环境信息

- OS信息： Windows10
- JDK信息： JDK-1.8
- 版本信息： spring-startup-analyzer  2.0.4

# 重现步骤

```java
final String filename = "一个60M的文件.pdf";
ClassPathResource classPathResource = new ClassPathResource(filename);
byte[] bytes = classPathResource.getInputStream().readAllBytes();

HashMap<String, String> res = new HashMap<>();
res.put("data", Base64Utils.encodeToString(bytes));
res.put("filename", filename);
String s = JSON.toJSONString(res);
```

# 期待的正确结果

预期情况，正常序列化。

# 相关日志输出
```log
 Exception in thread "StartupMonitor-Thread" java.lang.OutOfMemoryError
	at com.alibaba.fastjson2.JSONWriterUTF16.ensureCapacity(JSONWriterUTF16.java:1553)
	at com.alibaba.fastjson2.JSONWriterUTF16.writeStringEscape(JSONWriterUTF16.java:359)
	at com.alibaba.fastjson2.JSONWriterUTF16JDK8UF.writeString(JSONWriterUTF16JDK8UF.java:56)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:481)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1485)
	at io.github.linyimin0812.profiler.common.ui.StartupVO.toJSONString(StartupVO.java:59)
	at io.github.linyimin0812.profiler.core.container.IocContainer.writeStartupVOToHtml(IocContainer.java:108)
	at io.github.linyimin0812.profiler.core.container.IocContainer.stop(IocContainer.java:95)
	at io.github.linyimin0812.profiler.core.monitor.StartupMonitor.checkStatus(StartupMonitor.java:44)
```

# 建议处理方法

- 使用者根据需求修改 JVM 配置;
-  修改代码，可以使用 fastjson2 依赖中的 `JSONWriter.Feature.LargeObject` 来避免这个问题：
```java
// 这个是一个保护措施，是为了防止序列化有循环引用对象消耗过大资源的保护措施。
String s = JSONObject.toJSONString(res, JSONWriter.Feature.LargeObject);
```

**Comment by linyimin0812** [comment]
有兴趣提个PR嘛？
