### ISSUE TITLE
Mac(M1)下使用 Idea 方式启动 SpringBoot 应用报错

### ISSUE THREAD

**Issue by bugeamon** [linyimin0812/spring-startup-analyzer#4]
JVM： oracle-17.0.7

Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /xxxxx/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.one.profiler.AsyncProfiler.getInstance(AsyncProfiler.java:45)
	at io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.AsyncProfilerListener.start(AsyncProfilerListener.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.picocontainer.lifecycle.StartableLifecycleStrategy.doLifecycleMethod(StartableLifecycleStrategy.java:101)
	... 22 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at open/src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

**Comment by yufire** [comment]
**Java信息：**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)

**错误信息：**
七月 25, 2023 9:13:25 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
信息: command args: null
七月 25, 2023 9:13:25 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap createAgentClassLoader
信息: [file:/Users/yufire/spring-startup-analyzer/lib/spring-profiler-api.jar, file:/Users/yufire/spring-startup-analyzer/lib/spring-profiler-agent.jar, file:/Users/yufire/spring-startup-analyzer/lib/spring-profiler-common.jar, file:/Users/yufire/spring-startup-analyzer/lib/spring-profiler-core.jar, file:/Users/yufire/spring-startup-analyzer/lib/extension/spring-profiler-extension.jar, file:/Users/yufire/spring-startup-analyzer/lib/extension/spring-profiler-starter.jar]
七月 25, 2023 9:13:25 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
严重: Exception: null
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:63)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:55)
	... 6 more
Caused by: org.picocontainer.PicoLifecycleException: PicoLifecycleException: method 'public abstract void org.picocontainer.Startable.start()', instance 'io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.AsyncProfilerListener@7d9d1a19, java.lang.UnsatisfiedLinkError: /Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so: dlopen(/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so, 0x0001): tried: '/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (no such file), '/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at org.picocontainer.lifecycle.StartableLifecycleStrategy.doLifecycleMethod(StartableLifecycleStrategy.java:108)
	at org.picocontainer.lifecycle.StartableLifecycleStrategy.startComponent(StartableLifecycleStrategy.java:96)
	at org.picocontainer.lifecycle.StartableLifecycleStrategy.start(StartableLifecycleStrategy.java:87)
	at org.picocontainer.adapters.InstanceAdapter.start(InstanceAdapter.java:122)
	at org.picocontainer.adapters.InstanceAdapter.start(InstanceAdapter.java:100)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:554)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:501)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:488)
	at io.github.linyimin0812.profiler.core.container.IocContainer.start(IocContainer.java:62)
	at io.github.linyimin0812.profiler.core.enhance.ProfilerClassFileTransformer.<init>(ProfilerClassFileTransformer.java:49)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: /Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so: dlopen(/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so, 0x0001): tried: '/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (no such file), '/Users/yufire/spring-startup-analyzer/lib/extension/async-profiler/libasyncProfiler-mac.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:783)
	at java.lang.System.load(System.java:1100)
	at io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.one.profiler.AsyncProfiler.getInstance(AsyncProfiler.java:45)
	at io.github.linyimin0812.profiler.extension.enhance.asyncprofiler.AsyncProfilerListener.start(AsyncProfilerListener.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.StartableLifecycleStrategy.doLifecycleMethod(StartableLifecycleStrategy.java:101)
	... 21 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by linyimin0812** [comment]
> 

看日志应该是不支持arm架构

**Comment by bugeamon** [comment]
> 

这个 so 库，是使用的第三方的吗？应该是要换成对应的 .dylib 格式的库才能加载吧？

**Comment by bugeamon** [comment]
用 arthas 的仓库里 libasyncProfiler-mac.so 替换本仓库的 libasyncProfiler-mac.so 文件目前能够启动了，但是 x86 的没有试过，作者可以试一下  @linyimin0812

**Comment by linyimin0812** [comment]
> 用 arthas 的仓库里 libasyncProfiler-mac.so 替换本仓库的 libasyncProfiler-mac.so 文件目前能够启动了，但是 x86 的没有试过，作者可以试一下 @linyimin0812

谢谢尝试。async-profiler需要自己编译才行，因为添加了指定线程名采样和耗时计算的能力。Spring应用启动一般只需要关注main线程，直接使用arthas 的仓库里 libasyncProfiler-mac.so会采集所有的线程，这样数据太多

https://github.com/linyimin0812/async-profiler/tree/feat/20230505_support_sample_specify_thread_1

**Comment by linyimin0812** [comment]
> 用 arthas 的仓库里 libasyncProfiler-mac.so 替换本仓库的 libasyncProfiler-mac.so 文件目前能够启动了，但是 x86 的没有试过，作者可以试一下 @linyimin0812

有兴趣的话，可以编译一下https://github.com/linyimin0812/async-profiler/tree/feat/20230505_support_sample_specify_thread_1这个分支，再试试😀

**Comment by bugeamon** [comment]
> > 用 arthas 的仓库里 libasyncProfiler-mac.so 替换本仓库的 libasyncProfiler-mac.so 文件目前能够启动了，但是 x86 的没有试过，作者可以试一下 @linyimin0812
> 
> 有兴趣的话，可以编译一下[https://github.com/linyimin0812/async-profiler/tree/feat/20230505_support_sample_specify_thread_1这个分支，再试试😀](https://github.com/linyimin0812/async-profiler/tree/feat/20230505_support_sample_specify_thread_1%E8%BF%99%E4%B8%AA%E5%88%86%E6%94%AF%EF%BC%8C%E5%86%8D%E8%AF%95%E8%AF%95%F0%9F%98%80)

不好意思，这段时间太忙了，没注意邮件，我刚用你新编译的库文件试了一下，没问题了
