### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by lifesign** [linyimin0812/spring-startup-analyzer#82]
mac 版本，本地 jdk1.8，通过 idea 加载 vm option 方式，运行提示

```bash
/Users/demouser/.sdkman/candidates/java/8.0.232-trava/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:54066,suspend=y,server=n -javaagent:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-agent.jar -Dapp.name=test ...省略一些包 com.test.Application
Connected to the target VM, address: '127.0.0.1:54066', transport: 'socket'
九月 01, 2023 11:32:41 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
信息: command args: null
九月 01, 2023 11:32:42 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap createAgentClassLoader
信息: [file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-api.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-agent.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-common.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-core.jar, file:/Users/demouser/spring-startup-analyzer/lib/extension/spring-profiler-extension.jar, file:/Users/demouser/spring-startup-analyzer/lib/extension/spring-profiler-starter.jar]
Server listening on port 8065
九月 01, 2023 11:32:43 上午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
严重: Exception: null
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:60)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:56)
	... 6 more
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method java.lang.ClassLoader.findLoadedClass(Ljava/lang/String;)Ljava/lang/Class; from class io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader
	at io.github.linyimin0812.profiler.extension.enhance.invoke.InvokeDetailListener.filter(InvokeDetailListener.java:34)
	at io.github.linyimin0812.profiler.core.enhance.Matcher.isMatchClass(Matcher.java:58)
	at io.github.linyimin0812.profiler.core.enhance.ProfilerClassFileTransformer.retransformLoadedClass(ProfilerClassFileTransformer.java:115)
	... 11 more
Caused by: java.lang.IllegalAccessError: tried to access method java.lang.ClassLoader.findLoadedClass(Ljava/lang/String;)Ljava/lang/Class; from class io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader
	at io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader.loadClass(ProfilerAgentClassLoader.java:24)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
FATAL ERROR in native method: processing of -javaagent failed
Disconnected from the target VM, address: '127.0.0.1:54066', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```
```

**Comment by linyimin0812** [comment]
把`-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:54066,suspend=y,server=n`去掉或者使用传统调试参数的`-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=54066`试试呢

**Comment by lifesign** [comment]
> 把`-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:54066,suspend=y,server=n`去掉或者使用传统调试参数的`-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=54066`试试呢

这个是用 idea debug 模式启动自动带的，我改成单独的 run 也是报这个错误

**Comment by lifesign** [comment]
我使用命令行启动

```bash
➜ java -javaagent:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-agent.jar \
    -Dproject.name=mac-demo \
    -Dspring-startup-analyzer.admin.http.server.port=8066 \
    -jar /Users/demouser/Code/demo-project/startup/target/demo-project-startup-1.0.0-SNAPSHOT.jar
九月 01, 2023 3:04:12 下午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
信息: command args: null
九月 01, 2023 3:04:12 下午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap createAgentClassLoader
信息: [file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-api.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-agent.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-common.jar, file:/Users/demouser/spring-startup-analyzer/lib/spring-profiler-core.jar, file:/Users/demouser/spring-startup-analyzer/lib/extension/spring-profiler-extension.jar, file:/Users/demouser/spring-startup-analyzer/lib/extension/spring-profiler-starter.jar]
Server listening on port 8066
九月 01, 2023 3:04:13 下午 io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap premain
严重: Exception: null
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:60)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.linyimin0812.profiler.agent.ProfilerAgentBoostrap.premain(ProfilerAgentBoostrap.java:56)
	... 6 more
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method java.lang.ClassLoader.findLoadedClass(Ljava/lang/String;)Ljava/lang/Class; from class io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader
	at io.github.linyimin0812.profiler.extension.enhance.invoke.InvokeDetailListener.filter(InvokeDetailListener.java:34)
	at io.github.linyimin0812.profiler.core.enhance.Matcher.isMatchClass(Matcher.java:58)
	at io.github.linyimin0812.profiler.core.enhance.ProfilerClassFileTransformer.retransformLoadedClass(ProfilerClassFileTransformer.java:115)
	... 11 more
Caused by: java.lang.IllegalAccessError: tried to access method java.lang.ClassLoader.findLoadedClass(Ljava/lang/String;)Ljava/lang/Class; from class io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader
	at io.github.linyimin0812.profiler.agent.ProfilerAgentClassLoader.loadClass(ProfilerAgentClassLoader.java:24)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
FATAL ERROR in native method: processing of -javaagent failed
[1]    52452 abort      java  -Dproject.name=mac-demo  -jar
```

**Comment by linyimin0812** [comment]
方便提供一下应用的代码嘛？我自己的应用无法复现相关的问题

**Comment by lifesign** [comment]
> 方便提供一下应用的代码嘛？我自己的应用无法复现相关的问题

额 公司代码 不太行 那我换个代码试试看

**Comment by linyimin0812** [comment]
也可以看看/Users/demouser/spring-startup-analyzer/logs/startup.log日志文件下有没有其他错误信息

**Comment by linyimin0812** [comment]
定位到问题了，是不兼容trava-jdk-8导致的，可以换个非trava JDK如Oracle试试，后续再看一下怎么兼容

**Comment by linyimin0812** [comment]
#86

**Comment by lifesign** [comment]
> 定位到问题了，是不兼容trava-jdk-8导致的，可以换个非trava JDK如Oracle试试，后续再看一下怎么兼容

666，这个细节我忘记同步了，确实是用了 trava-jdk-8 因为有个插件需要支持热部署

**Comment by lifesign** [comment]
请问这个是还没打到最新版里么，早上试了下发现在问题依旧，看了下 install.sh 里的是老的 2.0.10，尝试手动下载 2.0.11 也不行

**Comment by linyimin0812** [comment]
> 请问这个是还没打到最新版里么，早上试了下发现在问题依旧，看了下 install.sh 里的是老的 2.0.10，尝试手动下载 2.0.11 也不行

还没发布最新版，可以先把`/Users/demouser/spring-startup-analyzer/config/spring-startup-analyzer.properties`中的`spring-startup-analyzer.invoke.count.methods`配置项删掉或者注释掉，这样就可以在trava-jdk-8 下使用

**Comment by linyimin0812** [comment]
> 请问这个是还没打到最新版里么，早上试了下发现在问题依旧，看了下 install.sh 里的是老的 2.0.10，尝试手动下载 2.0.11 也不行

v2.0.12已发布
